language: ruby
rvm:
  - 1.8.7
  - 1.9.2
  - 1.9.3
  - 2.0.0
  - jruby-18mode
  - jruby-19mode
  - rbx-18mode
  - rbx-19mode
gemfile:
  - gemfiles/Gemfile.paperclip-2.x
  - gemfiles/Gemfile.paperclip-3.x
matrix:
  exclude:
  - rvm: 1.8.7
    gemfile: gemfiles/Gemfile.paperclip-3.x
  - rvm: jruby-18mode
    gemfile: gemfiles/Gemfile.paperclip-3.x
  - rvm: rbx-18mode
    gemfile: gemfiles/Gemfile.paperclip-3.x
